New p3 from Steve Tarr
Major mods brought in from LogicPD and modified by Tarr for the P3.

diff --git a/mkconfig b/mkconfig
--- a/mkconfig
+++ b/mkconfig
@@ -12,53 +12,23 @@ APPEND=no	# Default: Create new config file
 BOARD_NAME=""	# Name to print in make output
 TARGETS=""
 
-arch=""
-cpu=""
-board=""
-vendor=""
-soc=""
-
-if [ \( $# -eq 2 \) -a \( "$1" = "-A" \) ] ; then
-	# Automatic mode
-	line=`egrep -i "^[[:space:]]*${2}[[:space:]]" boards.cfg` || {
-		echo "make: *** No rule to make target \`$2_config'.  Stop." >&2
-		exit 1
-	}
-
-	set ${line}
-	# add default board name if needed
-	[ $# = 3 ] && set ${line} ${1}
-fi
-
 while [ $# -gt 0 ] ; do
 	case "$1" in
 	--) shift ; break ;;
 	-a) shift ; APPEND=yes ;;
-	-n) shift ; BOARD_NAME="${1%_config}" ; shift ;;
+	-n) shift ; BOARD_NAME="${1%%_config}" ; shift ;;
 	-t) shift ; TARGETS="`echo $1 | sed 's:_: :g'` ${TARGETS}" ; shift ;;
 	*)  break ;;
 	esac
 done
 
+[ "${BOARD_NAME}" ] || BOARD_NAME="$1"
+
 [ $# -lt 4 ] && exit 1
 [ $# -gt 6 ] && exit 1
 
-CONFIG_NAME="${1%_config}"
-
-[ "${BOARD_NAME}" ] || BOARD_NAME="${CONFIG_NAME}"
-
-arch="$2"
-cpu="$3"
-if [ "$4" = "-" ] ; then
-	board=${BOARD_NAME}
-else
-	board="$4"
-fi
-[ $# -gt 4 ] && [ "$5" != "-" ] && vendor="$5"
-[ $# -gt 5 ] && [ "$6" != "-" ] && soc="$6"
-
-if [ "${ARCH}" -a "${ARCH}" != "${arch}" ]; then
-	echo "Failed: \$ARCH=${ARCH}, should be '${arch}' for ${BOARD_NAME}" 1>&2
+if [ "${ARCH}" -a "${ARCH}" != "$2" ]; then
+	echo "Failed: \$ARCH=${ARCH}, should be '$2' for ${BOARD_NAME}" 1>&2
 	exit 1
 fi
 
@@ -72,51 +42,53 @@ if [ "$SRCTREE" != "$OBJTREE" ] ; then
 	mkdir -p ${OBJTREE}/include2
 	cd ${OBJTREE}/include2
 	rm -f asm
-	ln -s ${SRCTREE}/arch/${arch}/include/asm asm
-	LNPREFIX=${SRCTREE}/arch/${arch}/include/asm/
+	ln -s ${SRCTREE}/include/asm-$2 asm
+	LNPREFIX="../../include2/asm/"
 	cd ../include
+	rm -rf asm-$2
 	rm -f asm
-	ln -s ${SRCTREE}/arch/${arch}/include/asm asm
+	mkdir asm-$2
+	ln -s asm-$2 asm
 else
 	cd ./include
 	rm -f asm
-	ln -s ../arch/${arch}/include/asm asm
+	ln -s asm-$2 asm
 fi
 
-rm -f asm/arch
+rm -f asm-$2/arch
 
-if [ -z "${soc}" ] ; then
-	ln -s ${LNPREFIX}arch-${cpu} asm/arch
+if [ -z "$6" -o "$6" = "NULL" ] ; then
+	ln -s ${LNPREFIX}arch-$3 asm-$2/arch
 else
-	ln -s ${LNPREFIX}arch-${soc} asm/arch
+	ln -s ${LNPREFIX}arch-$6 asm-$2/arch
 fi
 
-if [ "${arch}" = "arm" ] ; then
-	rm -f asm/proc
-	ln -s ${LNPREFIX}proc-armv asm/proc
+if [ "$2" = "arm" ] ; then
+	rm -f asm-$2/proc
+	ln -s ${LNPREFIX}proc-armv asm-$2/proc
 fi
 
 #
 # Create include file for Make
 #
-echo "ARCH   = ${arch}"  >  config.mk
-echo "CPU    = ${cpu}"   >> config.mk
-echo "BOARD  = ${board}" >> config.mk
+echo "ARCH   = $2" >  config.mk
+echo "CPU    = $3" >> config.mk
+echo "BOARD  = $4" >> config.mk
 
-[ "${vendor}" ] && echo "VENDOR = ${vendor}" >> config.mk
+[ "$5" ] && [ "$5" != "NULL" ] && echo "VENDOR = $5" >> config.mk
 
-[ "${soc}"    ] && echo "SOC    = ${soc}"    >> config.mk
-
-# Assign board directory to BOARDIR variable
-if [ -z "${vendor}" ] ; then
-    BOARDDIR=${board}
-else
-    BOARDDIR=${vendor}/${board}
-fi
+[ "$6" ] && [ "$6" != "NULL" ] && echo "SOC    = $6" >> config.mk
 
 #
 # Create board specific header file
 #
+if [ -f config.h ]; then
+    mv config.h config.h.bak
+    cp config.h.bak config.h
+else
+    touch config.h.bak
+fi
+
 if [ "$APPEND" = "yes" ]	# Append to existing config file
 then
 	echo >> config.h
@@ -129,11 +101,34 @@ for i in ${TARGETS} ; do
 	echo "#define CONFIG_MK_${i} 1" >>config.h ;
 done
 
-cat << EOF >> config.h
-#define CONFIG_BOARDDIR board/$BOARDDIR
-#include <config_defaults.h>
-#include <configs/${CONFIG_NAME}.h>
-#include <asm/config.h>
-EOF
+echo "#include <configs/$1.h>" >>config.h
+echo "#include <asm/config.h>" >>config.h
+
+#
+# Add TEXT_BASE from board config.mk in comment to config.h; this
+# causes config.h to change if the TEXT_BASE in board config.mk changes
+#
+config_mk=$SRCTREE/boards
+if [ "$VENDOR" != "" ]; then
+    config_mk=$config_mk/$VENDOR
+fi
+if [ "$BOARD" != "" ]; then
+    config_mk=$config_mk/$BOARD
+fi
+
+if [ -f $config_mk ]; then
+    TEXT_BASE=`grep TEXT_BASE $config_mk/config.mk`
+fi
+if [ ! -z "$TEXT_BASE" ]; then
+    echo "/* TEXT_BASE=$TEXT_BASE */" >> config.h
+else
+    rm config.h.bak
+fi
+
+cmp -s config.h config.h.bak && {
+    echo "Same config.h file..."
+    rm config.h
+    mv config.h.bak config.h
+}
 
 exit 0
